resources:
  - name: hello-git
    type: git
    source:
      uri: git@github.com:devopsguru0/hello-concourse.git
      branch: main

jobs:
  - name: say-hello
    plan:
      - get: hello-git
        trigger: true
      - task: print-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: hello-git
          run:
            path: sh
            args:
              - -exc
              - |
                echo "===> Hello from Concourse!"
                echo "===> Current commit:"
                cd hello-git
                git log -1 --oneline

